# Generated by Django 4.0.2 on 2022-02-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=100)),
                ('birth_place', models.CharField(max_length=100)),
                ('current_place', models.CharField(max_length=100)),
            ],
        ),
    ]
